# Generated by Django 6.0.6 on 2026-06-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro civil'), ('NIT', 'NIT')], default='CC', max_length=3, verbose_name='Tipo de documento')),
                ('documento', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de documento')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('?', '?')], max_length=3, verbose_name='Grupo sanguíneo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono / Celular')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, default='Medellín', max_length=100)),
                ('eps', models.CharField(blank=True, max_length=100, verbose_name='EPS / Aseguradora')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('es_menor', models.BooleanField(default=False, verbose_name='¿Es menor de edad?')),
                ('acudiente_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del acudiente')),
                ('acudiente_tipo_doc', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro civil'), ('NIT', 'NIT')], max_length=3, verbose_name='Tipo de doc. acudiente')),
                ('acudiente_documento', models.CharField(blank=True, max_length=20, verbose_name='Documento del acudiente')),
                ('acudiente_parentesco', models.CharField(blank=True, max_length=50, verbose_name='Parentesco')),
                ('acudiente_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del acudiente')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias conocidas')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos actuales')),
                ('antecedentes', models.TextField(blank=True, verbose_name='Antecedentes médicos relevantes')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales')),
                ('activo', models.BooleanField(default=True, verbose_name='Paciente activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['documento'], name='pacientes_p_documen_0a4e20_idx'), models.Index(fields=['apellidos', 'nombres'], name='pacientes_p_apellid_110dbb_idx')],
            },
        ),
    ]
