# Generated by Django 6.0.6 on 2026-06-17 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('ODONTOLOGO', 'Odontólogo'), ('AUXILIAR', 'Auxiliar')], default='AUXILIAR', max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('firma_digital', models.TextField(blank=True, verbose_name='Firma digital (PNG base64)')),
                ('tarjeta_profesional', models.CharField(blank=True, max_length=50, verbose_name='Número tarjeta profesional')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
