# Generated by Django 6.0.6 on 2026-06-17 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaConsentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('ORTODONCIA', 'Ortodoncia'), ('ENDODONCIA', 'Endodoncia'), ('EXODONCIA', 'Exodoncia'), ('IMPLANTE', 'Implante dental'), ('CIRUGIA', 'Cirugía oral'), ('PERIODONCIA', 'Periodoncia'), ('PROSTODONCIA', 'Prostodoncia'), ('BLANQUEAMIENTO', 'Blanqueamiento dental'), ('GENERAL', 'Procedimiento general'), ('OTRO', 'Otro')], default='GENERAL', max_length=20)),
                ('texto', models.TextField(help_text='Variables disponibles: {{paciente}}, {{documento}}, {{fecha}}, {{odontologo}}, {{procedimiento}}', verbose_name='Texto legal del consentimiento')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Versión')),
                ('requiere_autorizacion_expediente', models.BooleanField(default=True, verbose_name='Incluir casilla autorización expediente')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de consentimiento',
                'verbose_name_plural': 'Plantillas de consentimiento',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de firma'), ('FIRMADO', 'Firmado'), ('ANULADO', 'Anulado')], db_index=True, default='PENDIENTE', max_length=10)),
                ('texto_generado', models.TextField(blank=True, verbose_name='Texto del consentimiento al momento de firmar')),
                ('autoriza_expediente', models.BooleanField(blank=True, null=True, verbose_name='Autoriza uso del expediente')),
                ('firma_paciente', models.TextField(blank=True)),
                ('firma_acudiente', models.TextField(blank=True)),
                ('fecha_firma', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha y hora de firma')),
                ('ip_firma', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de firma')),
                ('dispositivo', models.CharField(blank=True, max_length=512, verbose_name='User-Agent del dispositivo')),
                ('hash_documento', models.CharField(blank=True, max_length=64, verbose_name='Hash SHA-256 de integridad')),
                ('pdf', models.FileField(blank=True, upload_to='consentimientos/%Y/%m/')),
                ('drive_url', models.URLField(blank=True, verbose_name='Enlace Google Drive')),
                ('enviado_correo', models.BooleanField(default=False, verbose_name='Enviado por correo')),
                ('enviado_whatsapp', models.BooleanField(default=False, verbose_name='Enviado por WhatsApp')),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio_whatsapp', models.DateTimeField(blank=True, null=True)),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas (no visibles para el paciente)')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos_como_odontologo', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='pacientes.paciente')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consentimientos.plantillaconsentimiento')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['paciente', 'estado'], name='consentimie_pacient_b9f6ed_idx'), models.Index(fields=['fecha_firma'], name='consentimie_fecha_f_7d7a90_idx')],
            },
        ),
    ]
