# Generated by Django 6.0.6 on 2026-06-17 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de consulta inicial')),
                ('enfermedad_actual', models.TextField(blank=True, verbose_name='Descripción de la enfermedad actual')),
                ('ultima_visita_odontologo', models.DateField(blank=True, null=True, verbose_name='Última visita al odontólogo')),
                ('tratamientos_previos', models.TextField(blank=True, verbose_name='Tratamientos odontológicos previos')),
                ('higiene_oral', models.CharField(blank=True, max_length=100, verbose_name='Frecuencia de cepillado')),
                ('usa_seda', models.BooleanField(default=False, verbose_name='Usa seda dental')),
                ('usa_enjuague', models.BooleanField(default=False, verbose_name='Usa enjuague bucal')),
                ('bruxismo', models.BooleanField(default=False, verbose_name='Bruxismo (rechinar dientes)')),
                ('succion_digital', models.BooleanField(default=False, verbose_name='Succión digital')),
                ('onicofagia', models.BooleanField(default=False, verbose_name='Onicofagia (comerse las uñas)')),
                ('habitos_descripcion', models.TextField(blank=True, verbose_name='Descripción de otros hábitos')),
                ('examen_extraoral', models.TextField(blank=True, verbose_name='Examen extraoral')),
                ('examen_intraoral', models.TextField(blank=True, verbose_name='Examen intraoral')),
                ('tejidos_blandos', models.TextField(blank=True, verbose_name='Tejidos blandos')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('plan_tratamiento', models.TextField(blank=True, verbose_name='Plan de tratamiento')),
                ('pronostico', models.TextField(blank=True, verbose_name='Pronóstico')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_creadas', to=settings.AUTH_USER_MODEL)),
                ('odontologo_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo principal')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ficha', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ficha clínica',
                'verbose_name_plural': 'Fichas clínicas',
            },
        ),
        migrations.CreateModel(
            name='EvolucionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima cita')),
                ('procedimiento', models.CharField(max_length=200, verbose_name='Procedimiento realizado')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('materiales_usados', models.TextField(blank=True, verbose_name='Materiales utilizados')),
                ('dientes_tratados', models.CharField(blank=True, max_length=100, verbose_name='Dientes tratados (ej: 11, 12, 21)')),
                ('valor_cobrado', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Valor cobrado (COP)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Indicaciones al paciente')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Odontólogo')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evoluciones', to='historial.fichaclinica')),
            ],
            options={
                'verbose_name': 'Evolución clínica',
                'verbose_name_plural': 'Evoluciones clínicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('datos', models.JSONField(default=dict, help_text='Mapa {numero_diente: {estado, notas, caras_afectadas}}', verbose_name='Datos del odontograma')),
                ('observaciones', models.TextField(blank=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odontogramas', to='historial.fichaclinica')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
                'ordering': ['-fecha'],
            },
        ),
    ]
